name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
paginate_path: "/blog/page:num/"
baseurl: /
domain_name: 'http://marcobacis.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'marcobacis'

# Details for the RSS feed generator
author:         'Marco Bacis'
authorTwitter:  'YourTwitterUsername'

permalink:       /blog/:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
